### ISSUE TITLE
example error: PsicquicSimpleExampleLimited.java

### ISSUE THREAD

**Issue by noedelta** [PSICQUIC/psicquic-client#1]
_From @GoogleCodeExporter on March 18, 2015 11:1_

```
What steps will reproduce the problem?
1. open the example in eclipse
2.
3.

What is the expected output? What do you see instead?
compiler error

What version of the PSICQUIC are you using?
psicquic-simple-client-1.0.jar

Please provide any additional information below.

where is the source file for psicquic-simple-client-1.0.jar

```

Original issue reported on code.google.com by `jianhua....@gmail.com` on 11 Oct 2011 at 11:28

_Copied from original issue: MICommunity/psicquic#25_

**Comment by noedelta** [comment]
_From @GoogleCodeExporter on March 18, 2015 11:1_

```
eclipse error:

Description	Resource	Path	Location	Type
The method getByQuery(String, String) in the type PsicquicSimpleClient is not 
applicable for the arguments (String, String, int, 
int)	PsicquicSimpleExampleLimited.java	/psicquic/src/org/hupo/psi/mi/psicquic/ws
client	line 43	Java Problem

```

Original comment by `jianhua....@gmail.com` on 11 Oct 2011 at 11:29

**Comment by bblodfon** [comment]
This issue should be on the psicquic-client-simple module :)
I don't believe it is still an issue and also there are no clear steps described to reproduce it.
